<?php

require_once dirname(__FILE__) . '/../../../lib/Sparrow/ValidationHelper.php';

/**
 * Test class for ValidationHelper.
 * Generated by PHPUnit on 2012-01-25 at 06:25:18.
 */
class ValidationHelperTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ValidationHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ValidationHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ('kioa',array('@')) == true.
     *
     * @covers ValidationHelper::is_alpha
     */
    public function testIs_alpha() {
        $this->assertEquals(
                true, ValidationHelper::is_alpha('kioa', array('@'))
        );
    }

    /**
     * @covers ValidationHelper::is_empty
     * @todo Implement testIs_empty().
     */
    public function testIs_empty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ValidationHelper::is_numeric
     * @todo Implement testIs_numeric().
     */
    public function testIs_numeric() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ValidationHelper::is_alphanumeric
     * @todo Implement testIs_alphanumeric().
     */
    public function testIs_alphanumeric() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ValidationHelper::is_valid_url
     * @todo Implement testIs_valid_url().
     */
    public function testIs_valid_url() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ValidationHelper::is_valid_email
     * @todo Implement testIs_valid_email().
     */
    public function testIs_valid_email() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ValidationHelper::is_valid_date
     * @todo Implement testIs_valid_date().
     */
    public function testIs_valid_date() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
